# Generated by Django 3.2 on 2021-12-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_reminder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinereminderregistration',
            name='gender',
            field=models.CharField(max_length=15),
        ),
    ]
