# Generated by Django 3.2 on 2021-12-18 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_reminder_app', '0003_vaccination_vaccinename'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinename',
            name='first_dose_age',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='vaccinename',
            name='fourth_dose_age',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='vaccinename',
            name='second_dose_age',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='vaccinename',
            name='third_dose_age',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dose_age', models.CharField(blank=True, max_length=32, null=True)),
                ('second_dose_age', models.CharField(blank=True, max_length=32, null=True)),
                ('third_dose_age', models.CharField(blank=True, max_length=32, null=True)),
                ('fourth_dose_age', models.CharField(blank=True, max_length=32, null=True)),
                ('first_dose_completed', models.BooleanField(default=False)),
                ('second_dose_completed', models.BooleanField(default=False)),
                ('third_dose_completed', models.BooleanField(default=False)),
                ('fourth_dose_completed', models.BooleanField(default=False)),
                ('vaccine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine_reminder_app.vaccinename')),
                ('vaccine_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine_reminder_app.vaccinereminderregistration')),
            ],
        ),
    ]
