# Generated by Django 3.2 on 2021-12-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_reminder_app', '0006_auto_20211218_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineschedule',
            name='first_dose_age',
        ),
        migrations.RemoveField(
            model_name='vaccineschedule',
            name='fourth_dose_age',
        ),
        migrations.RemoveField(
            model_name='vaccineschedule',
            name='second_dose_age',
        ),
        migrations.RemoveField(
            model_name='vaccineschedule',
            name='third_dose_age',
        ),
        migrations.AddField(
            model_name='vaccinename',
            name='first_dose_age',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='vaccinename',
            name='fourth_dose_age',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='vaccinename',
            name='second_dose_age',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='vaccinename',
            name='third_dose_age',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
