# Generated by Django 3.2 on 2021-12-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_reminder_app', '0008_auto_20211218_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinename',
            name='first_dose_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinename',
            name='fourth_dose_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinename',
            name='second_dose_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinename',
            name='third_dose_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
