# Generated by Django 3.2 on 2021-12-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_reminder_app', '0009_auto_20211218_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineschedule',
            name='first_dose_vaccine_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vaccineschedule',
            name='fourth_dose_vaccine_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vaccineschedule',
            name='second_dose_vaccine_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vaccineschedule',
            name='third_dose_vaccine_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
