# Generated by Django 3.2 on 2021-12-26 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_reminder_app', '0011_auto_20211218_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineschedule',
            name='vaccine_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine_reminder_app.vaccinename'),
        ),
    ]
