# Generated by Django 3.2 on 2021-12-28 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_reminder_app', '0013_alter_vaccineschedule_vaccine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineschedule',
            name='vaccine_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_name', to='vaccine_reminder_app.vaccinename'),
        ),
    ]
